image: golang:1.6

test:
  script:
  - mkdir -p $GOPATH/src/github.com/davars
  - cp -a . $GOPATH/src/github.com/davars/sohop
  - go get -t -v github.com/davars/sohop...
  - go test github.com/davars/sohop...